version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - start-dev
    networks:
      - keycloak_network

volumes:
  keycloak_data:

networks:
  keycloak_network: